---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# statcastr

The goal of `statcastr` is to make building a Statcast database easy. 

## Installation

You can install the released version of `statcastr` from [GitHub](https://www.github.com/beanumber/statcastr) with:

```{r, eval=FALSE}
devtools::install_github("beanumber/statcastr")
```

## Example

For example, once we set up a database connection...

```{r example, eval=TRUE, message=FALSE}
library(tidyverse)
library(statcastr)
db <- src_mysql_cnf(dbname = "statcastr")
sc <- etl("statcastr", db = db, dir = "~/dumps/statcastr")
```

...we can download the entire 2017 season's worth of data. 

```{r, eval=FALSE}
sc %>%
  etl_extract(year = 2017, month = 4:9) %>%
  etl_transform() %>%
  etl_load(tablenames = "statcast")
```

We now have a database containing 700,000 records.

```{r, warning=FALSE}
sc %>%
  tbl("statcast") %>%
  mutate(the_month = MONTH(STR_TO_DATE(game_date, "%Y-%m-%d"))) %>%
  group_by(the_month) %>%
  summarize(num_records = n(), 
            num_games = n_distinct(game_pk),
            num_teams = n_distinct(home_team), 
            barrel_pct = sum(barrel) / sum(barrel != "NA"))
```

